# Generated by Django 4.2.2 on 2023-06-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='img',
            field=models.ImageField(upload_to='images/%Y/%m/%d/'),
        ),
    ]
