# Generated by Django 4.2.2 on 2023-06-28 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Storage', '0002_discipline_info_alter_discipline_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='img',
        ),
    ]
