# Generated by Django 4.2.2 on 2023-06-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Storage', '0003_remove_discipline_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='info',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('info', models.TextField(blank=True, db_index=True)),
                ('time_upload', models.DateTimeField(auto_now=True)),
                ('upload', models.FileField(upload_to='upload_files/%Y/%m/%d')),
                ('discipline_id', models.ManyToManyField(null=True, to='Storage.discipline')),
            ],
        ),
    ]
