# Generated by Django 4.2.2 on 2023-06-28 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Storage', '0004_alter_discipline_info_alter_discipline_title_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='discipline_id',
        ),
        migrations.AddField(
            model_name='file',
            name='discipline_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Storage.discipline'),
        ),
    ]
